
services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: ronald-php
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
    ports:
      - "5173:5173"
    

  mysql:
    image: mysql:8.0
    container_name: ronald_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ronald_db
      MYSQL_USER: ronald_user
      MYSQL_PASSWORD: ronald_pass
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ronald-phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8082:80"
    depends_on:
      - mysql
  
  nginx:
    image: nginx:latest
    container_name: ronald-nginx
    ports:
    - "7000:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    
volumes:
  db_data:

